name: JPT's Statistics Export
version: "1.1.0"
slug: statistics_export
description: Export Home Assistant statistics to parquet
url: "https://github.com/JPT77/JPTs-Homeassist-Addons/
documentation: "https://github.com/JPT77/JPTs-Homeassist-Addons/blob/main/statistics_export/README.md"
changelog: "https://github.com/JPT77/JPTs-Homeassist-Addons/blob/main/statistics_export/CHANGELOG.md"
startup: services
boot: auto

arch:
  - amd64
  - aarch64

map:
  - config:ro
  - share:rw

options:
  export_hour: 1
  export_minute: 0
  keep_days: 28
  output_dir: "export"
  output_format: "parquet"

schema:
  export_hour: int
  export_minute: int
  keep_days: int
  output_dir: str
  output_format: list(parquet|csv|sql)
